### ISSUE TITLE
how to make clang-cl use lld?

### ISSUE THREAD

**Issue by microcai** [WubbaLubba/LlvmForVS2017#1]
how to make clang-cl use lld?

**Comment by Arik-Playground** [comment]
I'm not supporting using lld (for now at least), but you should be able to copy `lld-link.exe` from `%programfiles%\llvm\bin` to `%programfiles%\llvm\msbuild-bin` under the name `link.exe`, I belive that this will make msbuild use the lld as the linker

**Comment by zufuliu** [comment]
Some option like `-Xclang -fuse-ld=lld` might work, see the documet at https://lld.llvm.org/.
